WIP feat(zero-state): adds zero-state, icon-list and marketing-banner
RedHatInsights/insights-dashboard pull request #208
Opened 2020-11-09 21:30 UTC by mattnolting

As per discussion w/@ryelo, this PR will need some effort from the dashboard maintainers to complete. 

## Prerequisites

- [ ] Scope your styles to your individual card
- [ ] You are using translations when necessary with proper plural/singular modifications
- [ ] You are using the template card provided
- [ ] Use functional components & hooks (please)
- [ ] Attach screenshots (before and after)
- [ ] Make sure that all text in blue is populated with the correct link. If you're unsure what the url should be, just ask!

## What

This PR adds `ZeroState` layout, `IconList` and `MarketingBanner`.

## Screenshots

### Before
![Screen Shot 2020-11-09 at 10 20 15 AM](https://user-images.githubusercontent.com/5385435/98595664-47d42b00-22a4-11eb-9fdf-c2a51caa17ab.png)

### After
![Screen Shot 2020-11-09 at 3 57 45 PM](https://user-images.githubusercontent.com/5385435/98595716-57ec0a80-22a4-11eb-8adb-831bc413dab7.png)

## Code Review
@christiemolloy @ryelo @AllenBW

## Design Review
@kybaker

2020-11-10 12:31 UTC, AllenBW requested changes
flippin **BEAUTIFUL** @mattnolting!  Ah few general things off the bat...
* need to import dist versions of app deps (especially all the '@patternfly/react-core' ones)
* all strings need to be in Messages.js and then interpolated with intl
* an number of class components should be simplified to being functional components, (will also do away with the `this`)
* it does not appear that your zero state (when the workloadIs=SAP) supports any unique sap messaging, thinking the original message state should be kept until either, official sign off on doing away with sap specific messaging is approved, new sap messaging is approved 🤔 

🤗 🙇

2020-11-11 17:57 UTC, AllenBW commented
Ok doing feedback, push up a commit, gotta take a breather, s a lot, followup finishing translations coming up next!

2020-11-12 13:43 UTC, AllenBW commented
ok new ss after all mai playing around, as per @kybaker ah few text changes, but mostly the same

#### what it looks like
<img width="1639" alt="Screen Shot 2020-11-12 at 8 40 27 AM" src="https://user-images.githubusercontent.com/6640236/98947312-053c6980-24c3-11eb-9f72-ef2b7a58e3e8.png">
<img width="1637" alt="Screen Shot 2020-11-12 at 8 40 44 AM" src="https://user-images.githubusercontent.com/6640236/98947304-0372a600-24c3-11eb-857e-f32864e1802e.png">
<img width="706" alt="Screen Shot 2020-11-12 at 8 41 12 AM" src="https://user-images.githubusercontent.com/6640236/98947302-02da0f80-24c3-11eb-91d3-b057246148bf.png">
<img width="706" alt="Screen Shot 2020-11-12 at 8 41 29 AM" src="https://user-images.githubusercontent.com/6640236/98947293-01104c00-24c3-11eb-9861-7176dbc12b08.png">

2020-11-12 13:44 UTC, AllenBW approved these changes
Yes. 🆗 👌 🙆

2020-11-12 14:39 UTC, ryelo requested changes

2020-11-12 14:39 UTC, ryelo commented on locales/translations.json
> +  "dataPrivacyAndControls": "Red Hat Insights provides a mechanism for users to obtainactionable intelligence regarding suggested improvements todeployed Red Hat software. This document covers thesec
```suggestion
  "dataPrivacyAndControls": "Red Hat Insights provides a mechanism for users to obtain actionable intelligence regarding suggested improvements to deployed Red Hat software. This document covers the security measures Red Hat puts in place to provide secure transmission, processing, and analysis of this data by those tools.",
```

2020-11-12 14:39 UTC, ryelo commented on locales/translations.json
> +  "remediationsNoDataTitle": "You haven't created any remediation Playbooks yet",
```suggestion
  "remediationsNoDataTitle": "You haven't created any remediation playbooks yet",
```

2020-11-12 14:39 UTC, ryelo commented on locales/translations.json
> +  "smartManagement": "Smart management subscription enables push-button remediation of issuesidentified by Insights. Any issues identified by Insights are accompanied byremediation instructions, and
```suggestion
  "smartManagement": "Smart management subscription enables push-button remediation of issues identified by Insights. Any issues identified by Insights are accompanied by remediation instructions, and with Smart Management, remediation is available at scale.",
```

2020-11-12 14:39 UTC, ryelo commented on src/Messages.js
> +        defaultMessage: 'Smart management subscription enables push-button remediation of issuesidentified by Insights. Any issues identified by Insights are accompanied byremediation instructions, a
```suggestion
        defaultMessage: 'Smart management subscription enables push-button remediation of issues identified by Insights. Any issues identified by Insights are accompanied by remediation instructions, and with Smart Management, remediation is available at scale.'
```

2020-11-12 14:39 UTC, ryelo commented on src/Messages.js
> +        defaultMessage: 'Red Hat Insights provides a mechanism for users to obtainactionable intelligence regarding suggested improvements todeployed Red Hat software. This document covers thesecurit
```suggestion
        defaultMessage: 'Red Hat Insights provides a mechanism for users to obtain actionable intelligence regarding suggested improvements to deployed Red Hat software. This document covers the security measures Red Hat puts in place to provide secure transmission, processing, and analysis of this data by those tools.'
```

2020-11-12 14:39 UTC, ryelo commented on build/messages/src/Messages.json
> +    "defaultMessage": "Red Hat Insights provides a mechanism for users to obtainactionable intelligence regarding suggested improvements todeployed Red Hat software. This document covers thesecurity
```suggestion
    "defaultMessage": "Red Hat Insights provides a mechanism for users to obtain actionable intelligence regarding suggested improvements to deployed Red Hat software. This document covers the security measures Red Hat puts in place to provide secure transmission, processing, and analysis of this data by those tools.",
```

2020-11-12 14:39 UTC, ryelo commented on build/messages/src/Messages.json
> +    "defaultMessage": "Smart management subscription enables push-button remediation of issuesidentified by Insights. Any issues identified by Insights are accompanied byremediation instructions, and
```suggestion
    "defaultMessage": "Smart management subscription enables push-button remediation of issues identified by Insights. Any issues identified by Insights are accompanied by remediation instructions, and with Smart Management, remediation is available at scale.",
```

2020-11-12 14:39 UTC, ryelo commented on build/messages/src/Messages.json
> +    "defaultMessage": "Insights and smart management",
Should `smart management` be capitalized? It is in other places, so not sure of the casing.

2020-11-12 14:39 UTC, ryelo commented on locales/translations.json
> +  "insightsandsmartmanagement": "Insights and smart management",
Same thing with casing here

2020-11-12 14:39 UTC, ryelo commented on locales/translations.json
> +  "remediationsNoDataTitle": "You haven't created any remediation Playbooks yet",
playbooks is only capitalized when Ansible precedes it

2020-11-12 14:59 UTC, ryelo requested changes

2020-11-12 14:59 UTC, ryelo commented on build/messages/src/Messages.json
> +    "defaultMessage": "Insights and smart management",
Caps

2020-11-12 14:59 UTC, ryelo commented on build/messages/src/Messages.json
> +    "defaultMessage": "Smart management subscription enables push-button remediation of issues identified by Insights. Any issues identified by Insights are accompanied by remediation instructions, a
caps

2020-11-12 21:03 UTC, AllenBW commented
new ask, kill the cve table, here's what it looks like gone (left in the code cuz we'll wanta use that eventually)

<img width="1636" alt="Screen Shot 2020-11-12 at 4 01 31 PM" src="https://user-images.githubusercontent.com/6640236/98996278-93831080-2500-11eb-9634-7e7fa099a2f8.png">

2020-11-13 16:08 UTC, AllenBW approved these changes
Brilliant! 👍 💯 noicely done all <3

2020-11-13 16:34 UTC, merged