fix(table): updated pie chart + table styling
RedHatInsights/insights-dashboard pull request #248
Opened 2021-04-22 20:41 UTC by mattnolting

## Prerequisites

- [ ] Scope your styles to your individual card
- [ ] You are using translations when necessary with proper plural/singular modifications
- [ ] You are using the template card provided
- [ ] Use functional components & hooks (please)
- [ ] Attach screenshots (before and after)
- [ ] Make sure that all text in blue is populated with the correct link. If you're unsure what the url should be, just ask!

## What
Fixes tooltip in table wrapping. Unbroke layout.

## Screenshots

### Before

<img width="1314" alt="Screen Shot 2021-04-22 at 4 36 06 PM" src="https://user-images.githubusercontent.com/5385435/115781825-e9e65c00-a388-11eb-87d4-66b67af24488.png">

<img width="1310" alt="Screen Shot 2021-04-22 at 4 36 17 PM" src="https://user-images.githubusercontent.com/5385435/115781846-f1a60080-a388-11eb-973f-ae709c8b4f1a.png">

<img width="1313" alt="Screen Shot 2021-04-22 at 4 36 23 PM" src="https://user-images.githubusercontent.com/5385435/115781855-f4a0f100-a388-11eb-86e3-319af8858439.png">

<img width="432" alt="Screen Shot 2021-04-22 at 4 37 59 PM" src="https://user-images.githubusercontent.com/5385435/115781996-1ef2ae80-a389-11eb-94ad-7f2af469933c.png">

<img width="455" alt="Screen Shot 2021-04-22 at 4 37 27 PM" src="https://user-images.githubusercontent.com/5385435/115781938-0bdfde80-a389-11eb-893c-ab2aa1bab41b.png">

### After

<img width="1354" alt="Screen Shot 2021-04-22 at 4 39 24 PM" src="https://user-images.githubusercontent.com/5385435/115782313-8872bd00-a389-11eb-83e8-e35a6f95e1f8.png">

<img width="1354" alt="Screen Shot 2021-04-22 at 4 39 40 PM" src="https://user-images.githubusercontent.com/5385435/115782322-8b6dad80-a389-11eb-81e1-25bf104dcd31.png">

<img width="561" alt="Screen Shot 2021-04-22 at 4 40 07 PM" src="https://user-images.githubusercontent.com/5385435/115782330-8e689e00-a389-11eb-8d01-a2f31e9246fd.png">

<img width="564" alt="Screen Shot 2021-04-22 at 4 40 15 PM" src="https://user-images.githubusercontent.com/5385435/115782338-90caf800-a389-11eb-881a-2c081ec9b2a1.png">

<img width="579" alt="Screen Shot 2021-04-22 at 4 40 22 PM" src="https://user-images.githubusercontent.com/5385435/115782345-93c5e880-a389-11eb-91b0-846e67e024f0.png">

## Additional Info
[if needed]

## Code Review
@ryelo @AllenBW

## Design Review
@kybaker

2021-04-22 20:44 UTC, kybaker commented
@mattnolting Looks excellent - ship it!

2021-04-26 12:29 UTC, AllenBW requested changes
@mattnolting ah few feedback items, also if yer gonna change the info tooltip in two places, oughta change it in the third so everything looks the same (advisor info tooltip is still a button)

alsoooo after taking a look, just wanted to confirm, this work is focused on making cards more compact when displayed in smaller viewports?

2021-04-26 12:29 UTC, AllenBW commented on src/PresentationalComponents/Template/DataListItemTemplate.js
> +                            Newly released security rule &nbsp;<DateFormat type='onlyDate' date={dataListItemTemplateDate} />
Lets keep these strings translated

2021-04-26 12:29 UTC, AllenBW commented on src/PresentationalComponents/Template/DataListItemTemplate.scss
> +    // .ins-c-dashboard-data-list__title-row {
commented code needs killing

2021-04-26 12:29 UTC, AllenBW commented on src/SmartComponents/NewRules/NewRules.scss
> +    display: none;
goooood catch

2021-04-27 12:19 UTC, AllenBW commented
@mattnolting still some linting to work through

2021-04-27 13:39 UTC, AllenBW approved these changes
👍 will push to prod beta immediately, prod-stable this eve

2021-04-27 13:40 UTC, merged