Link "Configure integations" button to Communications tab
RedHatInsights/insights-dashboard pull request #484
Opened 2024-05-07 11:45 UTC by leSamo

https://issues.redhat.com/browse/RHINENG-3595

2024-05-07 20:03 UTC, johnsonm325 requested changes
I think you left off the `s` by accident.

2024-05-07 20:03 UTC, johnsonm325 commented on src/SmartComponents/SystemInventory/SystemInventoryHeader.js
> +                                    <Link to="/settings/integration?category=Communications">
```suggestion
                                    <Link to="/settings/integrations?category=Communications">
```

2024-05-09 15:57 UTC, leSamo commented on src/SmartComponents/SystemInventory/SystemInventoryHeader.js
> +                                    <Link to="/settings/integration?category=Communications">
Good catch! You are right

2024-05-13 12:17 UTC, mkholjuraev approved these changes
LGTM!

2024-05-13 13:28 UTC, merged